---
esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  min_version: "2024.6.1"
  on_boot:
    then:
      - uart.write:
          id: handset_uart
          data: [ 0xA5, 0x00, 0x00, 0x01, 0x01 ]
  project:
    name: tj_horner.upsy_desky
    version: "4.0.4"

uart:
  id: handset_uart
  tx_pin: 18
  rx_pin: 17
  baud_rate: 9600
  stop_bits: 1
  parity: NONE
  
esp32:
  board: esp32dev
  framework:
    type: esp-idf

substitutions:
  name: upsy-desky
  friendly_name: Upsy Desky
  desk_height_name: Desk Height
  target_desk_height_name: Target Desk Height
  standing_desk_uart_rx_pin: "17"
  standing_desk_up_pin: "21"
  standing_desk_down_pin: "22"
  standing_desk_key_pin: "16"
  standing_desk_min_height: "62"
  standing_desk_max_height: "128"
  button_bit1_pin: "21"
  button_bit2_pin: "22"
  button_bit4_pin: "19"
  button_m_pin: "20"
  default_height_units: cm

packages:
  standing_desk: github://tjhorner/esphome-standing-desk/configs/template.yaml
  addon_presets: !include addons/presets.yaml
  addon_stable_ids: !include addons/stable-ids.yaml
  addon_runtime_config: !include addons/runtime-config.yaml

button:
  - platform: restart
    name: "Restart"

light:
  - platform: status_led
    id: upsy_desky_status_led
    name: "Status LED"
    pin: GPIO23
    restore_mode: RESTORE_DEFAULT_ON
